Add lastExecutedBy to sync rule table like creation date
EyeSeeTea/metadata-synchronization pull request #838
Opened 2021-03-08 14:57 UTC by jvfdunkley

### :pushpin: References

-   **Issue:** Closes ["Add "lastExecutedBy" to sync rule table like "creation date""](https://app.clickup.com/t/f8z013) in ClickUp

### :memo: Implementation
- Added lastExecutedBy to GenericSyncUseCase to update when a sync rule has been executed. I combined the update method to update both lastExecuted and lastExecutedBy at the same time
- LastExecutedBy is an automatically displayed column in SyncRulesListPage

### :art: Screenshots
<img width="1258" alt="Screen Shot 2021-03-08 at 3 55 59 PM" src="https://user-images.githubusercontent.com/20975863/110337990-cbb9dc00-8026-11eb-9d63-9fa48081a59a.png">

### :fire: Is there anything the reviewer should know to test it?

### :bookmark_tabs: Others

-   Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

-   Any change in the [D2 Api](https://github.com/EyeSeeTea/d2-api)? If so, what branch/PR?

2021-03-09 09:04 UTC, adrianq commented
@jvfdunkley there a bunch of conflicts between your branch and development. Not sure what you used as your base branch... Can you please resolve these conflicts?

2021-03-09 12:14 UTC, EyeSeeTeaBotTest commented
<h3>Tests failed with errors :rotating_light:</h3><br />Build commit Merge ad42a5bec4a175d6ae408d8fc067beb7c49f2e51 into 52a41988d313899f7552507f4af56ca357f71b4c with commit id c10a8c6d276fe545073fe7e0ead23a6d15f555c4 on branch feature/add-lastExecuteBy-to-sync-rule-table<br /><br />Travis log available at <a href=https://travis-ci.org/EyeSeeTea/metadata-synchronization/builds/762125078 target=_blank>builds/762125078</a><br /><br />See cypress results at <a href=https://eyeseetea.github.io/feedback-ci/EyeSeeTea/metadata-synchronization/pr/838/c10a8c6d276fe545073fe7e0ead23a6d15f555c4 target=_blank>feedback-ci/EyeSeeTea/metadata-synchronization/pr/838/c10a8c6d276fe545073fe7e0ead23a6d15f555c4</a>

2021-03-10 09:56 UTC, SferaDev commented on src/domain/rules/entities/SynchronizationRule.ts
> +
```suggestion
```

2021-03-10 09:57 UTC, SferaDev commented on src/domain/rules/entities/SynchronizationRule.ts
> +        return this.syncRule.lastExecutedBy?.name || undefined;
We would normally return directly { id: string; name: string } instead of string

2021-03-10 09:59 UTC, SferaDev commented on src/domain/rules/entities/SynchronizationRule.ts
> +    public updateLastExecuted(lastExecuted: Date, id: string, name: string): SynchronizationRule {
Instead of ``id: string, name: string`` we probably want ``lastUpdatedBy: NamedRef``

2021-03-10 10:00 UTC, SferaDev commented on src/domain/rules/entities/SynchronizationRule.ts
> +    lastExecutedBy?: { id: string; name: string };
This might be a ``NamedRef``

2021-03-10 10:01 UTC, SferaDev commented
Thanks @jvfdunkley, added some comments to code. Overall looks great!

2021-03-10 20:19 UTC, adrianq requested changes
@jvfdunkley This feature seems not to be working for new sync rules. I just created a new rule and it seems to be failing due to the new fields being undefined. Can you please have a look at it? 
![image](https://user-images.githubusercontent.com/6850223/110692060-d8346500-81dd-11eb-93cc-c62e7b5fb905.png)

2021-03-11 09:16 UTC, merged