exclude default categories from dataElements
EyeSeeTea/metadata-synchronization pull request #959
Opened 2024-06-08 17:16 UTC by eperedo

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8694rjjmk

### :memo: Implementation

In DHIS 2.38.6 the defaults parameter is not working in the `metadata` endpoint
`/api/metadata.json?fields=id&filter=id:eq:data_element_id&categoryCombo&defaults=INCLUDE/EXCLUDE;`
so I'm manually removing the default `categoryCombo` from `dataElements`

### :video_camera: Screenshots/Screen capture

![image](https://github.com/EyeSeeTea/metadata-synchronization/assets/461124/189cf7a4-0f6a-450a-9ebe-25964f24e675)

### :fire: Is there anything the reviewer should know to test it?

### :bookmark_tabs: Others

#8694rjjmk

2024-06-08 17:16 UTC, ifoche commented
Task linked: [CU-8694rjjmk MDSync is generating the default category](https://app.clickup.com/t/8694rjjmk)

2024-06-10 07:19 UTC, MiquelAdell approved these changes

2024-06-10 11:58 UTC, tokland requested changes

2024-06-10 11:58 UTC, tokland commented on src/domain/metadata/usecases/MetadataSyncUseCase.ts
> +                const elementWithoutDefaults =
A use case should not make any reference to DHIS2 (that's an implementation detail). If DHIS2 has a bug (Indeed, I've checked it: 2.36 OK, 2.38 FAIL), any extra processing should be done in the data layer, probably the metadata DHIS2 repositoriy (or any other file which calls the API with that option `defaults: boolean`  -> I've found also utils/synchronization.ts)

Note: checking dhis2-core, DefaultCategoryService.java, the models that have a default object are the 4 expected: category, categoryOption, categoryCombo, categoryOptionCombo.

2024-06-11 09:02 UTC, tokland approved these changes
[code-only review] All good. I'd just move the file (not a major issue)

2024-06-11 09:02 UTC, tokland commented on src/utils/d2-utils.ts
> +
Let's move the file to data/ so it's more CleanArch compliant.

2024-06-12 08:38 UTC, MiquelAdell commented
I guess @eperedo commit fixes @tokland request, does it? I've re-requested the review from Arnau

2024-06-12 08:39 UTC, tokland approved these changes
Nothing more to add, it's ok by me now.

2024-06-12 09:25 UTC, merged