Remove non essential data from sync payload
EyeSeeTea/metadata-synchronization pull request #968
Opened 2024-08-07 10:01 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes 
- https://app.clickup.com/t/8694y8dhy
- https://app.clickup.com/t/869584vj9

### :memo: Implementation
- [x] Add a filter to remove non essential user data i.e. `created`, `createdBy`, `lastUpdated`, `lastUpdatedBy`
- [x] Add a filter to remove default category objects

### :video_camera: Screenshots/Screen capture

2024-08-07 10:02 UTC, ifoche commented
Task linked: [CU-8694y8dhy Add option to filter out non esencial user related data](https://app.clickup.com/t/8694y8dhy)
Task linked: [CU-869584vj9 Add option to filter out default option category](https://app.clickup.com/t/869584vj9)

2025-02-18 09:48 UTC, xurxodev requested changes
Thanks @deeonwuli 

My first test has been sync a category with new sync params non-active. This configuration should work like in development branch.

It's not working 

This is my test in develoment branch
<img width="1919" alt="Screenshot 2025-02-18 at 07 46 55" src="https://github.com/user-attachments/assets/95b92c6f-3b52-43ba-b31c-53f6f5a69bbb" />

This is my test in your branch
<img width="1142" alt="Screenshot 2025-02-18 at 07 54 32" src="https://github.com/user-attachments/assets/a8a6c1f3-2ee5-43fb-805b-ed66bc85d78c" />
<img width="1920" alt="Screenshot 2025-02-18 at 07 55 19" src="https://github.com/user-attachments/assets/1b5f3086-f655-4cef-aadc-3824de8dc33e" />

Can you review it? Please test from development and from your branch to compare results

2025-02-25 13:04 UTC, xurxodev requested changes
thanks @deeonwuli 

The GitHub action is broken. I've added a fix and it's merged. Can you bring development changes with this fix and solve conflicts to follow with the review?

2025-03-31 18:40 UTC, 9sneha-n commented
> thanks @deeonwuli
> 
> The GitHub action is broken. I've added a fix and it's merged. Can you bring development changes with this fix and solve conflicts to follow with the review?

@xurxodev I will be taking over this PR from dumebi. I have resolved the conflicts and tested by selecting the option and downloading the json and comparing - it is correctly removing the last updated and created by data. Please let me know if this seems correct or any other testing is required.  
<img width="1728" alt="Screenshot 2025-04-01 at 12 05 33 AM" src="https://github.com/user-attachments/assets/b6ff1b0f-f5fb-4699-b146-28f6cd687027" />
<img width="1728" alt="Screenshot 2025-04-01 at 12 05 42 AM" src="https://github.com/user-attachments/assets/0eade5d6-964f-4189-8b0c-bf4aa4466401" />
<img width="1728" alt="Screenshot 2025-04-01 at 12 06 04 AM" src="https://github.com/user-attachments/assets/1c25ad5f-28a2-43b9-8dd0-41816b38540b" />
Also, looks like we are not giving a proper summary if the new options are selected in the last screen, please let me know if this change is required : 
<img width="1251" alt="Screenshot 2025-04-01 at 12 03 48 AM" src="https://github.com/user-attachments/assets/8e4ed89d-2a49-4d1d-a4b3-d564a5e83665" />

2025-04-01 11:34 UTC, xurxodev requested changes
.

2025-04-02 08:06 UTC, 9sneha-n commented
> Thanks @9sneha-n
> 
> Several things to comment:
> 
> * Now we have the problem, because in this PR [Feature/migrate references or full objects #989](https://github.com/EyeSeeTea/metadata-synchronization/pull/989) I moved all metadata toggles to select dependencies step in this PR .
> * I think that added new toggles in this PR should be in the dependencies step where now should be all metadata toggles
> * And yes I think the summary should be fixed
> 
> But I think that we need the opinion and validation of @adrianq to do this.

Thanks @xurxodev . 
So after the latest changes, we need to move these 2 options : "Remove default categories, categoryOptions, categoryCombos and categoryOptionCombos", "Remove lastUpdated, lastUpdatedBy, created and createdBys" to "Select Dependencies" tab seen below : 
<img width="1281" alt="Screenshot 2025-04-02 at 1 35 15 PM" src="https://github.com/user-attachments/assets/98be3a06-d748-4104-9ac8-67a666bd8d92" />
@adrianq Let me know if you see any concerns with this, if not, i will move the options to "Select Dependencies" tab

2025-04-02 08:26 UTC, adrianq commented
@xurxodev Your comments make complete sense. However, as discussed with @9sneha-n I think it makes more sense to review and merge this PR https://github.com/EyeSeeTea/metadata-synchronization/pull/999  and then do the appropriate changes in this branch

2025-04-16 10:05 UTC, xurxodev approved these changes
thanks @9sneha-n and @deeonwuli 

@adrianq remember create a task to move new toggles to the metadata step

2025-04-24 07:59 UTC, merged