[fix]: Maintain objectsTable column selection
EyeSeeTea/metadata-synchronization pull request #978
Opened 2024-12-09 13:54 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8696884gq

### :memo: Implementation
- [x] get and save visible objectsTable columns to the user data store

### :video_camera: Screenshots/Screen capture

https://github.com/user-attachments/assets/166175d2-5ecf-4c54-aca7-93cd28d28531

### :bookmark_tabs: Others

#8696884gq

2024-12-09 13:54 UTC, ifoche commented
Task linked: [CU-8696884gq Unable to Maintain Column Header Selection when Selecting Events in v.2.19.1](https://app.clickup.com/t/8696884gq)

2025-02-05 22:55 UTC, eperedo requested changes
[code review only] Some comments about clean arch. Let me know if you have any questions. Thanks @deeonwuli

2025-02-07 01:47 UTC, eperedo approved these changes
[code only review] Looks good, just a minor comment about the name of methods in repository, but without any impact in the code. Thanks @deeonwuli!

2025-02-07 01:47 UTC, eperedo commented on src/domain/table-columns/repositories/TableColumnsRepository.ts
> +}
No need to change since it was my proposal, just a note for the future:

I forgot to remove the name of the entity in the methods:

getColumns -> get
saveColumns -> save

because the repository's name `TableColumnsRepository` already implies that the operations are related to `TableColumns` the method names can be shortened to get and save without losing clarity.

Another example in the [skeleton app](https://github.com/EyeSeeTea/dhis2-app-skeleton/blob/master/src/domain/repositories/UserRepository.ts#L5) `getCurrent` instead `getCurrentUser`

2025-02-11 12:24 UTC, MiquelAdell requested changes
the fix is not working for me. More info on clickup

2025-02-12 11:35 UTC, MiquelAdell approved these changes
This fixed it, thanks

2025-02-12 11:35 UTC, merged